#!/bin/bash -

node_name=$1

# Remove ip addr from waveform interface to reassign to batman interface
ip addr flush dev ${waveform_interface}

batctl meshif bat0 interface add bat0

%if batman_orig_interval:
batctl meshif bat0 orig_interval ${batman_orig_interval}
%endif

ip addr add 10.100.0.${etce_index}/24 dev bat0
ip link set bat0 up

if [ -f batman-routes ]
then
    ./batman-routes $node_name
fi